option(ENABLE_COVERAGE "Enable code coverage instrumentation" OFF)

if(WIN32)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if (NOT DEFINED ENV{LLVM_LIB})
            message(FATAL_ERROR "LLVM_LIB is not set")
        endif()
        link_directories("$ENV{LLVM_LIB}")

        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
        set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
        set(CMAKE_C_DEPENDS_USE_COMPILER FALSE)
        set(CMAKE_CXX_DEPENDS_USE_COMPILER FALSE)
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF)

        if(ENABLE_COVERAGE)
            add_compile_options(-fprofile-instr-generate -fcoverage-mapping)
            add_link_options(-fprofile-instr-generate)
        endif()
    endif()
elseif(UNIX)
    if(ENABLE_COVERAGE)
        add_compile_options(--coverage -fprofile-update=atomic)
        add_link_options(--coverage)
    endif()
else()
    message(WARNING "[${projectName}] Unsupported platform")
endif()

message("[${projectName}] CMAKE_CXX_FLAGS: [${CMAKE_CXX_FLAGS}]")
message("[${projectName}] ENABLE_ASAN_UBSAN: [${ENABLE_ASAN_UBSAN}]")
message("[${projectName}] ENABLE_COVERAGE: [${ENABLE_COVERAGE}]")
