if(WIN32)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        if (NOT DEFINED ENV{LLVM_LIB})
            message(FATAL_ERROR "LLVM_LIB is not set")
        endif()
        link_directories("$ENV{LLVM_LIB}")

        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreadedDLL")
        set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
        set(CMAKE_C_DEPENDS_USE_COMPILER FALSE)
        set(CMAKE_CXX_DEPENDS_USE_COMPILER FALSE)
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF)
    endif()
elseif(UNIX)
    # Linux / macOS — GCC or Clang, no extra linker directories needed
else()
    message(WARNING "[${projectName}] Unsupported platform")
endif()

message("[${projectName}] CMAKE_CXX_FLAGS: [${CMAKE_CXX_FLAGS}]")
message("[${projectName}] ENABLE_ASAN_UBSAN: [${ENABLE_ASAN_UBSAN}]")
